name: wgrest
description: Wireguard rest api client
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^4.2.1
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^4.2.1
  build_runner: null

flutter:
  uses-material-design: true